### ISSUE TITLE
Unexpected token on chrome

### ISSUE THREAD

**Issue by JamesANZ** [hotwallet/hotwallet#139]
2.c169738e.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
main.328d595d.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'

On hotwallet.com

**Comment by will123195** [comment]
I am unable to reproduce. Those filenames seem to be outdated. Maybe you are seeing an old cached version of the webpage html?

Could you please post the contents of `2.c169738e.chunk.js`? I expect there will be an error message that may offer a clue about what is going on.

**Comment by JamesANZ** [comment]
@will123195 indeed. It is a caching issue. Cheers.
